//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Appalachia.Prototype/asset/Input/InputActions/KOCInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Appalachia.Prototype.KOC.Application.Input
{
    public partial class @KOCInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @KOCInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""KOCInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""351f2ccd-1f9f-44bf-9bec-d62ac5c5f408"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""6b444451-8a00-4d00-a97e-f47457f736a8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""6c2ab1b8-8984-453a-af3d-a3c78ae1679a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""978bfe49-cc26-4a3d-ab7b-7d7a29327403"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""00ca640b-d935-4593-8157-c05846ea39b3"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e2062cb9-1b15-46a2-838c-2f8d72a0bdd9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d2581a9b-1d11-4566-b27d-b92aff5fabbc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""320bffee-a40b-4347-ac70-c210eb8bc73a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fcfe95b8-67b9-4526-84b5-5d0bc98d6400"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""3a01fb3c-f37a-4d1f-bbe8-0e6b609ef550"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ec4898e6-9bc6-4a59-a1a8-1d7a9080c209"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a76ab3b5-b311-43a0-b664-eeff668c93ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4a045483-6b35-4a5a-a5f2-22dcc7d0c6d5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""deba1b5f-cafb-4f03-a01f-dc1ee3fa5367"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c1f7a91b-d0fd-4a62-997e-7fb9b69bf235"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8e490b-c610-4785-884f-f04217b23ca4"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143bb1cd-cc10-4eca-a2f0-a3664166fe91"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05f6913d-c316-48b2-a6bb-e225f14c7960"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""033e1767-5bd2-4be6-b360-4ea0a68ea9cd"",
            ""actions"": [
                {
                    ""name"": ""Screenshot"",
                    ""type"": ""Button"",
                    ""id"": ""3a6e67bf-ae32-46dc-9279-866528af3792"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Debug Log"",
                    ""type"": ""Button"",
                    ""id"": ""7e24db0c-6283-4461-bc0f-56639659a438"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Graphy"",
                    ""type"": ""Button"",
                    ""id"": ""7920063e-4a89-451a-b64c-25e44a0526fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Graphy Mode"",
                    ""type"": ""Button"",
                    ""id"": ""0be3e2a2-5c9e-412a-89b1-a4fc48edad45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cedd2789-1ba2-4a15-98f8-6d14ac704732"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Screenshot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99dc8417-d312-4429-9420-fcfa413a2f13"",
                    ""path"": ""<Keyboard>/f11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Debug Log"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""808c0870-e236-4a23-8679-432011f719f7"",
                    ""path"": ""<Keyboard>/f9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Graphy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48498484-c9a8-4ab4-b5f6-d39e993383df"",
                    ""path"": ""<Keyboard>/f10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Graphy Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Main Menu"",
            ""id"": ""92b3f68b-28e8-4eae-a3c9-af2b754b02ff"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Generic Menu"",
            ""id"": ""48201dbc-5bc0-44cc-afc5-537b1baebc79"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b9fe3d28-207d-4eef-8c6e-9e054cd9fd07"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""581f8abc-1fe2-4b2b-960f-d419c3432964"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""365cb05e-4f05-4577-8db4-728d7f93f3f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9d3d2938-0088-444c-821a-c4f90f788d9f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0d9863ba-28cd-4fbf-aa16-f52fa94fe9ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""e295eae9-2344-486c-8816-d4a3618ee0ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Apply"",
                    ""type"": ""Button"",
                    ""id"": ""8dbc084e-bfbd-4de9-89b6-5063868df0ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Default"",
                    ""type"": ""Button"",
                    ""id"": ""f6845a4f-8232-4b54-92e5-f4f604550af2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81bd6971-82a0-4dfc-87fb-ee9156a2fad9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba4a9133-16ab-4535-9194-17520b9a13a1"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b532fcf4-5930-49cc-bab8-0d5770f16096"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32f7d2f3-781d-4970-b22e-34776d9eeffc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82b98e86-23bd-488f-9cf7-599384d1cfea"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97b231c6-93ba-4473-a4be-3d087d23427d"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6425a54-097e-4974-b3c9-cb9d2dcbd9bd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d375cd3-7190-4c36-a9d2-f090236acefc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""719e18b1-1498-4359-b0a0-8377be3164a8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80b028c0-01f8-4d68-8e65-89cf71d44295"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d71eab41-d280-433d-9621-dff032555b3c"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fbb1c59-46df-47c7-8ba4-2041057c72e3"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""874e4c24-62f2-47ce-a50f-43a4ce4caa39"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0ea670d-94e9-4227-ab99-cc22c13b8134"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Apply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95446493-fecb-4cde-8149-75c477b1722d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Apply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32f527c9-cab5-4a92-8141-047e1180f1ba"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Apply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f99ab9e5-da37-40b4-b1e7-f3ab50909215"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Default"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80345161-1d2a-4d0c-aa4c-2f1501d8f9dd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Default"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""7edcf829-bcb0-4c5e-bdda-7a3dce656e09"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9604adda-881e-4fbd-9409-5c4a28c8654f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""61b56622-2fbc-495d-a816-85fc86141af5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b7c07b8-d92f-4206-866e-9a180aec9abd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7dde17b3-d5e8-468e-a557-0b51cadf42e7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""24594428-40d1-47f0-88fe-45cc67f058fc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d58132a5-c0db-4895-a135-0c77b7fed348"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1fd976e3-c323-4033-ab08-c81c981fe5d6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""50ac4996-c9fb-4942-b754-9fcf8a6c0f5a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a70b125a-3dcc-4a50-bb49-76d015f2d4ed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""2905e6ec-b9e9-4932-8b3f-fff9191a336b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""DPad"",
                    ""id"": ""25bd3e33-d6bd-4d10-b3d0-e161ec282b39"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4c9a95f3-b4eb-4386-80c1-5963366f1e5d"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d0b5026a-9bd6-43cc-afac-f3f82a65cc57"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7c4a6674-1410-42bb-b302-c405bf589aa5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4a662b57-d0a1-4b2b-8525-b1c05cf07b84"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""6eae28b5-15ea-413a-a505-2fd7853d6564"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f7e3b6aa-b439-44e2-9b51-0a42dbd90954"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6d9ca97d-b0d3-4f9f-86f8-f57884ee4be0"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""465d7e81-7c37-4408-9a5b-92dca23c5f39"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c13eb578-1177-47af-ad59-1c9c87aba17a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""In Game Menu"",
            ""id"": ""fd43d7c9-7140-4e43-86a7-348a2551acce"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Pause Menu"",
            ""id"": ""386407dd-e095-4140-9a18-7d52e332e4b3"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Death Menu"",
            ""id"": ""eb77f6bd-81b9-4f35-9546-bf849b66a36f"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Loading Screen"",
            ""id"": ""0dec1137-8c33-4696-b10f-9fc391cffd62"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
            m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
            // Debug
            m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
            m_Debug_Screenshot = m_Debug.FindAction("Screenshot", throwIfNotFound: true);
            m_Debug_ToggleDebugLog = m_Debug.FindAction("Toggle Debug Log", throwIfNotFound: true);
            m_Debug_ToggleGraphy = m_Debug.FindAction("Toggle Graphy", throwIfNotFound: true);
            m_Debug_ToggleGraphyMode = m_Debug.FindAction("Toggle Graphy Mode", throwIfNotFound: true);
            // Main Menu
            m_MainMenu = asset.FindActionMap("Main Menu", throwIfNotFound: true);
            // Generic Menu
            m_GenericMenu = asset.FindActionMap("Generic Menu", throwIfNotFound: true);
            m_GenericMenu_Navigate = m_GenericMenu.FindAction("Navigate", throwIfNotFound: true);
            m_GenericMenu_Submit = m_GenericMenu.FindAction("Submit", throwIfNotFound: true);
            m_GenericMenu_Cancel = m_GenericMenu.FindAction("Cancel", throwIfNotFound: true);
            m_GenericMenu_Point = m_GenericMenu.FindAction("Point", throwIfNotFound: true);
            m_GenericMenu_Click = m_GenericMenu.FindAction("Click", throwIfNotFound: true);
            m_GenericMenu_Back = m_GenericMenu.FindAction("Back", throwIfNotFound: true);
            m_GenericMenu_Apply = m_GenericMenu.FindAction("Apply", throwIfNotFound: true);
            m_GenericMenu_Default = m_GenericMenu.FindAction("Default", throwIfNotFound: true);
            // In Game Menu
            m_InGameMenu = asset.FindActionMap("In Game Menu", throwIfNotFound: true);
            // Pause Menu
            m_PauseMenu = asset.FindActionMap("Pause Menu", throwIfNotFound: true);
            // Death Menu
            m_DeathMenu = asset.FindActionMap("Death Menu", throwIfNotFound: true);
            // Loading Screen
            m_LoadingScreen = asset.FindActionMap("Loading Screen", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_Look;
        private readonly InputAction m_Player_Fire;
        public struct PlayerActions
        {
            private @KOCInputActions m_Wrapper;
            public PlayerActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @Look => m_Wrapper.m_Player_Look;
            public InputAction @Fire => m_Wrapper.m_Player_Fire;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                    @Fire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                    @Fire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                    @Fire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @Fire.started += instance.OnFire;
                    @Fire.performed += instance.OnFire;
                    @Fire.canceled += instance.OnFire;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // Debug
        private readonly InputActionMap m_Debug;
        private IDebugActions m_DebugActionsCallbackInterface;
        private readonly InputAction m_Debug_Screenshot;
        private readonly InputAction m_Debug_ToggleDebugLog;
        private readonly InputAction m_Debug_ToggleGraphy;
        private readonly InputAction m_Debug_ToggleGraphyMode;
        public struct DebugActions
        {
            private @KOCInputActions m_Wrapper;
            public DebugActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Screenshot => m_Wrapper.m_Debug_Screenshot;
            public InputAction @ToggleDebugLog => m_Wrapper.m_Debug_ToggleDebugLog;
            public InputAction @ToggleGraphy => m_Wrapper.m_Debug_ToggleGraphy;
            public InputAction @ToggleGraphyMode => m_Wrapper.m_Debug_ToggleGraphyMode;
            public InputActionMap Get() { return m_Wrapper.m_Debug; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
            public void SetCallbacks(IDebugActions instance)
            {
                if (m_Wrapper.m_DebugActionsCallbackInterface != null)
                {
                    @Screenshot.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnScreenshot;
                    @Screenshot.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnScreenshot;
                    @Screenshot.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnScreenshot;
                    @ToggleDebugLog.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleDebugLog;
                    @ToggleDebugLog.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleDebugLog;
                    @ToggleDebugLog.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleDebugLog;
                    @ToggleGraphy.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleGraphy;
                    @ToggleGraphy.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleGraphy;
                    @ToggleGraphy.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleGraphy;
                    @ToggleGraphyMode.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleGraphyMode;
                    @ToggleGraphyMode.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleGraphyMode;
                    @ToggleGraphyMode.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleGraphyMode;
                }
                m_Wrapper.m_DebugActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Screenshot.started += instance.OnScreenshot;
                    @Screenshot.performed += instance.OnScreenshot;
                    @Screenshot.canceled += instance.OnScreenshot;
                    @ToggleDebugLog.started += instance.OnToggleDebugLog;
                    @ToggleDebugLog.performed += instance.OnToggleDebugLog;
                    @ToggleDebugLog.canceled += instance.OnToggleDebugLog;
                    @ToggleGraphy.started += instance.OnToggleGraphy;
                    @ToggleGraphy.performed += instance.OnToggleGraphy;
                    @ToggleGraphy.canceled += instance.OnToggleGraphy;
                    @ToggleGraphyMode.started += instance.OnToggleGraphyMode;
                    @ToggleGraphyMode.performed += instance.OnToggleGraphyMode;
                    @ToggleGraphyMode.canceled += instance.OnToggleGraphyMode;
                }
            }
        }
        public DebugActions @Debug => new DebugActions(this);

        // Main Menu
        private readonly InputActionMap m_MainMenu;
        private IMainMenuActions m_MainMenuActionsCallbackInterface;
        public struct MainMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public MainMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
            public void SetCallbacks(IMainMenuActions instance)
            {
                if (m_Wrapper.m_MainMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_MainMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public MainMenuActions @MainMenu => new MainMenuActions(this);

        // Generic Menu
        private readonly InputActionMap m_GenericMenu;
        private IGenericMenuActions m_GenericMenuActionsCallbackInterface;
        private readonly InputAction m_GenericMenu_Navigate;
        private readonly InputAction m_GenericMenu_Submit;
        private readonly InputAction m_GenericMenu_Cancel;
        private readonly InputAction m_GenericMenu_Point;
        private readonly InputAction m_GenericMenu_Click;
        private readonly InputAction m_GenericMenu_Back;
        private readonly InputAction m_GenericMenu_Apply;
        private readonly InputAction m_GenericMenu_Default;
        public struct GenericMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public GenericMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_GenericMenu_Navigate;
            public InputAction @Submit => m_Wrapper.m_GenericMenu_Submit;
            public InputAction @Cancel => m_Wrapper.m_GenericMenu_Cancel;
            public InputAction @Point => m_Wrapper.m_GenericMenu_Point;
            public InputAction @Click => m_Wrapper.m_GenericMenu_Click;
            public InputAction @Back => m_Wrapper.m_GenericMenu_Back;
            public InputAction @Apply => m_Wrapper.m_GenericMenu_Apply;
            public InputAction @Default => m_Wrapper.m_GenericMenu_Default;
            public InputActionMap Get() { return m_Wrapper.m_GenericMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GenericMenuActions set) { return set.Get(); }
            public void SetCallbacks(IGenericMenuActions instance)
            {
                if (m_Wrapper.m_GenericMenuActionsCallbackInterface != null)
                {
                    @Navigate.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnNavigate;
                    @Navigate.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnNavigate;
                    @Navigate.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnNavigate;
                    @Submit.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnSubmit;
                    @Submit.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnSubmit;
                    @Submit.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnSubmit;
                    @Cancel.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnCancel;
                    @Cancel.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnCancel;
                    @Cancel.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnCancel;
                    @Point.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnPoint;
                    @Point.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnPoint;
                    @Point.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnPoint;
                    @Click.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnClick;
                    @Click.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnClick;
                    @Click.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnClick;
                    @Back.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnBack;
                    @Back.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnBack;
                    @Back.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnBack;
                    @Apply.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnApply;
                    @Apply.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnApply;
                    @Apply.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnApply;
                    @Default.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnDefault;
                    @Default.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnDefault;
                    @Default.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnDefault;
                }
                m_Wrapper.m_GenericMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Navigate.started += instance.OnNavigate;
                    @Navigate.performed += instance.OnNavigate;
                    @Navigate.canceled += instance.OnNavigate;
                    @Submit.started += instance.OnSubmit;
                    @Submit.performed += instance.OnSubmit;
                    @Submit.canceled += instance.OnSubmit;
                    @Cancel.started += instance.OnCancel;
                    @Cancel.performed += instance.OnCancel;
                    @Cancel.canceled += instance.OnCancel;
                    @Point.started += instance.OnPoint;
                    @Point.performed += instance.OnPoint;
                    @Point.canceled += instance.OnPoint;
                    @Click.started += instance.OnClick;
                    @Click.performed += instance.OnClick;
                    @Click.canceled += instance.OnClick;
                    @Back.started += instance.OnBack;
                    @Back.performed += instance.OnBack;
                    @Back.canceled += instance.OnBack;
                    @Apply.started += instance.OnApply;
                    @Apply.performed += instance.OnApply;
                    @Apply.canceled += instance.OnApply;
                    @Default.started += instance.OnDefault;
                    @Default.performed += instance.OnDefault;
                    @Default.canceled += instance.OnDefault;
                }
            }
        }
        public GenericMenuActions @GenericMenu => new GenericMenuActions(this);

        // In Game Menu
        private readonly InputActionMap m_InGameMenu;
        private IInGameMenuActions m_InGameMenuActionsCallbackInterface;
        public struct InGameMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public InGameMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_InGameMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(InGameMenuActions set) { return set.Get(); }
            public void SetCallbacks(IInGameMenuActions instance)
            {
                if (m_Wrapper.m_InGameMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_InGameMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public InGameMenuActions @InGameMenu => new InGameMenuActions(this);

        // Pause Menu
        private readonly InputActionMap m_PauseMenu;
        private IPauseMenuActions m_PauseMenuActionsCallbackInterface;
        public struct PauseMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public PauseMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_PauseMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PauseMenuActions set) { return set.Get(); }
            public void SetCallbacks(IPauseMenuActions instance)
            {
                if (m_Wrapper.m_PauseMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_PauseMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public PauseMenuActions @PauseMenu => new PauseMenuActions(this);

        // Death Menu
        private readonly InputActionMap m_DeathMenu;
        private IDeathMenuActions m_DeathMenuActionsCallbackInterface;
        public struct DeathMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public DeathMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_DeathMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DeathMenuActions set) { return set.Get(); }
            public void SetCallbacks(IDeathMenuActions instance)
            {
                if (m_Wrapper.m_DeathMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_DeathMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public DeathMenuActions @DeathMenu => new DeathMenuActions(this);

        // Loading Screen
        private readonly InputActionMap m_LoadingScreen;
        private ILoadingScreenActions m_LoadingScreenActionsCallbackInterface;
        public struct LoadingScreenActions
        {
            private @KOCInputActions m_Wrapper;
            public LoadingScreenActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_LoadingScreen; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LoadingScreenActions set) { return set.Get(); }
            public void SetCallbacks(ILoadingScreenActions instance)
            {
                if (m_Wrapper.m_LoadingScreenActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_LoadingScreenActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public LoadingScreenActions @LoadingScreen => new LoadingScreenActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnFire(InputAction.CallbackContext context);
        }
        public interface IDebugActions
        {
            void OnScreenshot(InputAction.CallbackContext context);
            void OnToggleDebugLog(InputAction.CallbackContext context);
            void OnToggleGraphy(InputAction.CallbackContext context);
            void OnToggleGraphyMode(InputAction.CallbackContext context);
        }
        public interface IMainMenuActions
        {
        }
        public interface IGenericMenuActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnBack(InputAction.CallbackContext context);
            void OnApply(InputAction.CallbackContext context);
            void OnDefault(InputAction.CallbackContext context);
        }
        public interface IInGameMenuActions
        {
        }
        public interface IPauseMenuActions
        {
        }
        public interface IDeathMenuActions
        {
        }
        public interface ILoadingScreenActions
        {
        }
    }
}
