//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Appalachia.Prototype/asset/Input/InputActions/KOCInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Appalachia.Prototype.KOC.Input
{
    public partial class @KOCInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @KOCInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""KOCInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""351f2ccd-1f9f-44bf-9bec-d62ac5c5f408"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""6b444451-8a00-4d00-a97e-f47457f736a8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""6c2ab1b8-8984-453a-af3d-a3c78ae1679a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""978bfe49-cc26-4a3d-ab7b-7d7a29327403"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""00ca640b-d935-4593-8157-c05846ea39b3"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e2062cb9-1b15-46a2-838c-2f8d72a0bdd9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d2581a9b-1d11-4566-b27d-b92aff5fabbc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""320bffee-a40b-4347-ac70-c210eb8bc73a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fcfe95b8-67b9-4526-84b5-5d0bc98d6400"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""3a01fb3c-f37a-4d1f-bbe8-0e6b609ef550"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ec4898e6-9bc6-4a59-a1a8-1d7a9080c209"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a76ab3b5-b311-43a0-b664-eeff668c93ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4a045483-6b35-4a5a-a5f2-22dcc7d0c6d5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""deba1b5f-cafb-4f03-a01f-dc1ee3fa5367"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c1f7a91b-d0fd-4a62-997e-7fb9b69bf235"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8e490b-c610-4785-884f-f04217b23ca4"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143bb1cd-cc10-4eca-a2f0-a3664166fe91"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05f6913d-c316-48b2-a6bb-e225f14c7960"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Developer Interface"",
            ""id"": ""033e1767-5bd2-4be6-b360-4ea0a68ea9cd"",
            ""actions"": [
                {
                    ""name"": ""Toggle Developer Interface"",
                    ""type"": ""Button"",
                    ""id"": ""7e24db0c-6283-4461-bc0f-56639659a438"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open Command Palette"",
                    ""type"": ""Button"",
                    ""id"": ""0cddf666-77fb-49a9-8587-92b13f4b81a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Menu Bar"",
                    ""type"": ""Button"",
                    ""id"": ""7920063e-4a89-451a-b64c-25e44a0526fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Status Bar"",
                    ""type"": ""Button"",
                    ""id"": ""0be3e2a2-5c9e-412a-89b1-a4fc48edad45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Activity Bar"",
                    ""type"": ""Button"",
                    ""id"": ""d12b9954-6b48-4761-a152-effe82f86194"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Side Bar"",
                    ""type"": ""Button"",
                    ""id"": ""921e25e9-d8ad-426a-a260-64a45f947d47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Panel"",
                    ""type"": ""Button"",
                    ""id"": ""c84a34ca-215e-4a75-a37c-351d07632fe2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Screenshot"",
                    ""type"": ""Button"",
                    ""id"": ""3a6e67bf-ae32-46dc-9279-866528af3792"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""2e503210-dab8-45b9-a08b-4bb4ca657a26"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Developer Interface"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""d15b8b35-d9c6-4af2-ba7b-2bfd1f879986"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Developer Interface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""0ce995f1-35c4-4e0b-89ae-7aedc3148aa2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Developer Interface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""72788a81-e8eb-48df-b82f-ec71f8993d39"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Developer Interface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""f4d4061b-39ba-4277-bcb2-cac1d6828a98"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Menu Bar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""a3c514aa-1417-4852-8bbc-2a121447ed20"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Menu Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""1d274b3d-3ba1-40ad-9465-47d21398bed1"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Menu Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""17a89b9d-7b2e-4b16-bd95-48dfd4238928"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Menu Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""207d2751-321a-420a-90b5-fab7a9261828"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Status Bar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""a0e23ff7-b927-4a10-ae4e-c7c46e2a9d60"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Status Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""ea17cb7a-52fd-4a70-ac1c-7dfbb260989a"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Status Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e4b95e1b-8d50-4746-8b2a-a77e4abd0c7f"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Status Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cedd2789-1ba2-4a15-98f8-6d14ac704732"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Screenshot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""0f28ca70-66c2-44af-adfc-47101793dc4b"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Activity Bar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""20d19975-c68c-4830-acb4-ce6822c9b1c9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Activity Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""9d09a07d-49f8-402d-ac67-55eb0123b477"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Activity Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b5299d33-60dc-4118-a31a-a5404a68d855"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Activity Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""bb4bb504-b991-4b84-b9a3-e61d9bfaecef"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Side Bar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""e27ede11-438b-48c2-8695-0f070a76f920"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Side Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""5fcdae00-963e-4984-886d-a0eabe4489d4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Side Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d6d5e8c8-ff8a-4db0-afd9-d4aea923651b"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Side Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""53e48697-d562-42d7-94d0-8752917fe737"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Panel"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""d4bc05a3-5bc9-46c0-aeaa-e168d7c3390c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""2f34f764-7446-4a43-aaed-e7b4e19ddbde"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bc60adc1-6d7c-4e19-b238-7c4e078b690e"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Toggle Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""82387da6-98b3-4e92-923c-8decba3a6402"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Command Palette"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""6c731368-46bd-4933-a88c-850f19903e08"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Open Command Palette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""a998b0ec-c799-4555-bde8-8afc69433733"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Open Command Palette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4887e4df-d86b-45aa-9e9d-5336b7864724"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Open Command Palette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Main Menu"",
            ""id"": ""92b3f68b-28e8-4eae-a3c9-af2b754b02ff"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Generic Menu"",
            ""id"": ""48201dbc-5bc0-44cc-afc5-537b1baebc79"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b9fe3d28-207d-4eef-8c6e-9e054cd9fd07"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""581f8abc-1fe2-4b2b-960f-d419c3432964"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""365cb05e-4f05-4577-8db4-728d7f93f3f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9d3d2938-0088-444c-821a-c4f90f788d9f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0d9863ba-28cd-4fbf-aa16-f52fa94fe9ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""e295eae9-2344-486c-8816-d4a3618ee0ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Apply"",
                    ""type"": ""Button"",
                    ""id"": ""8dbc084e-bfbd-4de9-89b6-5063868df0ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Default"",
                    ""type"": ""Button"",
                    ""id"": ""f6845a4f-8232-4b54-92e5-f4f604550af2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81bd6971-82a0-4dfc-87fb-ee9156a2fad9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba4a9133-16ab-4535-9194-17520b9a13a1"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b532fcf4-5930-49cc-bab8-0d5770f16096"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32f7d2f3-781d-4970-b22e-34776d9eeffc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82b98e86-23bd-488f-9cf7-599384d1cfea"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97b231c6-93ba-4473-a4be-3d087d23427d"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6425a54-097e-4974-b3c9-cb9d2dcbd9bd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d375cd3-7190-4c36-a9d2-f090236acefc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""719e18b1-1498-4359-b0a0-8377be3164a8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80b028c0-01f8-4d68-8e65-89cf71d44295"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d71eab41-d280-433d-9621-dff032555b3c"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fbb1c59-46df-47c7-8ba4-2041057c72e3"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""874e4c24-62f2-47ce-a50f-43a4ce4caa39"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0ea670d-94e9-4227-ab99-cc22c13b8134"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Apply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95446493-fecb-4cde-8149-75c477b1722d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Apply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32f527c9-cab5-4a92-8141-047e1180f1ba"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Apply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f99ab9e5-da37-40b4-b1e7-f3ab50909215"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Default"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80345161-1d2a-4d0c-aa4c-2f1501d8f9dd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Default"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""7edcf829-bcb0-4c5e-bdda-7a3dce656e09"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9604adda-881e-4fbd-9409-5c4a28c8654f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""61b56622-2fbc-495d-a816-85fc86141af5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b7c07b8-d92f-4206-866e-9a180aec9abd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7dde17b3-d5e8-468e-a557-0b51cadf42e7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""24594428-40d1-47f0-88fe-45cc67f058fc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d58132a5-c0db-4895-a135-0c77b7fed348"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1fd976e3-c323-4033-ab08-c81c981fe5d6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""50ac4996-c9fb-4942-b754-9fcf8a6c0f5a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a70b125a-3dcc-4a50-bb49-76d015f2d4ed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""2905e6ec-b9e9-4932-8b3f-fff9191a336b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""DPad"",
                    ""id"": ""25bd3e33-d6bd-4d10-b3d0-e161ec282b39"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4c9a95f3-b4eb-4386-80c1-5963366f1e5d"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d0b5026a-9bd6-43cc-afac-f3f82a65cc57"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7c4a6674-1410-42bb-b302-c405bf589aa5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4a662b57-d0a1-4b2b-8525-b1c05cf07b84"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""6eae28b5-15ea-413a-a505-2fd7853d6564"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f7e3b6aa-b439-44e2-9b51-0a42dbd90954"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6d9ca97d-b0d3-4f9f-86f8-f57884ee4be0"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""465d7e81-7c37-4408-9a5b-92dca23c5f39"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c13eb578-1177-47af-ad59-1c9c87aba17a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""In Game Menu"",
            ""id"": ""fd43d7c9-7140-4e43-86a7-348a2551acce"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Pause Menu"",
            ""id"": ""386407dd-e095-4140-9a18-7d52e332e4b3"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Death Menu"",
            ""id"": ""eb77f6bd-81b9-4f35-9546-bf849b66a36f"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Loading Screen"",
            ""id"": ""0dec1137-8c33-4696-b10f-9fc391cffd62"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Splash Screen"",
            ""id"": ""059f762b-e4d5-4fa9-baad-e7d02c58561e"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""a5733590-4361-4e92-92fc-95729e80c6dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3910d083-2e75-4b3f-9eba-3dfe58ee97bd"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13d3eeb3-203c-42d5-adff-526d57873676"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee1f429a-b242-4c54-9740-16502f35bad3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39bc6878-2ccd-4717-adae-7af101e48a63"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c05c71a-06c6-46ca-a80b-ca4948cd3de2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61924ce3-a321-48bc-9f2b-cd6111e103c0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84c61f4a-2786-43e6-b45b-4130c45ffb16"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e8b8740-301b-46e2-aaf9-9042f782d0dc"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e7cc657-2d59-48ff-9d14-e7d81e9d010d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7497606-707b-4030-9bad-9926a878b4f0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""259cadd7-42e5-4183-98e2-c52ca1f9c72c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""544e05aa-a324-4022-8bec-030552925dd5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""487013b1-4fb2-48fb-9d77-c0134e77bc75"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bbc535f-135b-4c04-948c-7699afa9ed21"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f47679d-ec0f-411e-ae45-5cf6d1b07fc7"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Start Screen"",
            ""id"": ""1c0e4289-ac86-4d3c-b9b8-65d3b9f55b3c"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""d42d9c49-4397-433a-bfaf-2181e40d86ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b8d88e16-06e4-48b3-a2f1-faaa9f1e7155"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50cbd24d-5489-4c8d-a248-696fb431f8d5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a7fbe6c-bcf4-40ac-879d-7d269a0f33d0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""109d0563-1272-4105-b528-67419c3eb234"",
                    ""path"": ""<Mouse>/*"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4929c7cf-23b2-46e8-9132-4da61af7dd89"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cec67595-851a-46df-a503-f8a7e4697183"",
                    ""path"": ""<Gamepad>/*"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
            m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
            // Developer Interface
            m_DeveloperInterface = asset.FindActionMap("Developer Interface", throwIfNotFound: true);
            m_DeveloperInterface_ToggleDeveloperInterface = m_DeveloperInterface.FindAction("Toggle Developer Interface", throwIfNotFound: true);
            m_DeveloperInterface_OpenCommandPalette = m_DeveloperInterface.FindAction("Open Command Palette", throwIfNotFound: true);
            m_DeveloperInterface_ToggleMenuBar = m_DeveloperInterface.FindAction("Toggle Menu Bar", throwIfNotFound: true);
            m_DeveloperInterface_ToggleStatusBar = m_DeveloperInterface.FindAction("Toggle Status Bar", throwIfNotFound: true);
            m_DeveloperInterface_ToggleActivityBar = m_DeveloperInterface.FindAction("Toggle Activity Bar", throwIfNotFound: true);
            m_DeveloperInterface_ToggleSideBar = m_DeveloperInterface.FindAction("Toggle Side Bar", throwIfNotFound: true);
            m_DeveloperInterface_TogglePanel = m_DeveloperInterface.FindAction("Toggle Panel", throwIfNotFound: true);
            m_DeveloperInterface_Screenshot = m_DeveloperInterface.FindAction("Screenshot", throwIfNotFound: true);
            // Main Menu
            m_MainMenu = asset.FindActionMap("Main Menu", throwIfNotFound: true);
            // Generic Menu
            m_GenericMenu = asset.FindActionMap("Generic Menu", throwIfNotFound: true);
            m_GenericMenu_Navigate = m_GenericMenu.FindAction("Navigate", throwIfNotFound: true);
            m_GenericMenu_Submit = m_GenericMenu.FindAction("Submit", throwIfNotFound: true);
            m_GenericMenu_Cancel = m_GenericMenu.FindAction("Cancel", throwIfNotFound: true);
            m_GenericMenu_Point = m_GenericMenu.FindAction("Point", throwIfNotFound: true);
            m_GenericMenu_Click = m_GenericMenu.FindAction("Click", throwIfNotFound: true);
            m_GenericMenu_Back = m_GenericMenu.FindAction("Back", throwIfNotFound: true);
            m_GenericMenu_Apply = m_GenericMenu.FindAction("Apply", throwIfNotFound: true);
            m_GenericMenu_Default = m_GenericMenu.FindAction("Default", throwIfNotFound: true);
            // In Game Menu
            m_InGameMenu = asset.FindActionMap("In Game Menu", throwIfNotFound: true);
            // Pause Menu
            m_PauseMenu = asset.FindActionMap("Pause Menu", throwIfNotFound: true);
            // Death Menu
            m_DeathMenu = asset.FindActionMap("Death Menu", throwIfNotFound: true);
            // Loading Screen
            m_LoadingScreen = asset.FindActionMap("Loading Screen", throwIfNotFound: true);
            // Splash Screen
            m_SplashScreen = asset.FindActionMap("Splash Screen", throwIfNotFound: true);
            m_SplashScreen_Continue = m_SplashScreen.FindAction("Continue", throwIfNotFound: true);
            // Start Screen
            m_StartScreen = asset.FindActionMap("Start Screen", throwIfNotFound: true);
            m_StartScreen_Continue = m_StartScreen.FindAction("Continue", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_Look;
        private readonly InputAction m_Player_Fire;
        public struct PlayerActions
        {
            private @KOCInputActions m_Wrapper;
            public PlayerActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @Look => m_Wrapper.m_Player_Look;
            public InputAction @Fire => m_Wrapper.m_Player_Fire;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                    @Fire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                    @Fire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                    @Fire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @Fire.started += instance.OnFire;
                    @Fire.performed += instance.OnFire;
                    @Fire.canceled += instance.OnFire;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // Developer Interface
        private readonly InputActionMap m_DeveloperInterface;
        private IDeveloperInterfaceActions m_DeveloperInterfaceActionsCallbackInterface;
        private readonly InputAction m_DeveloperInterface_ToggleDeveloperInterface;
        private readonly InputAction m_DeveloperInterface_OpenCommandPalette;
        private readonly InputAction m_DeveloperInterface_ToggleMenuBar;
        private readonly InputAction m_DeveloperInterface_ToggleStatusBar;
        private readonly InputAction m_DeveloperInterface_ToggleActivityBar;
        private readonly InputAction m_DeveloperInterface_ToggleSideBar;
        private readonly InputAction m_DeveloperInterface_TogglePanel;
        private readonly InputAction m_DeveloperInterface_Screenshot;
        public struct DeveloperInterfaceActions
        {
            private @KOCInputActions m_Wrapper;
            public DeveloperInterfaceActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @ToggleDeveloperInterface => m_Wrapper.m_DeveloperInterface_ToggleDeveloperInterface;
            public InputAction @OpenCommandPalette => m_Wrapper.m_DeveloperInterface_OpenCommandPalette;
            public InputAction @ToggleMenuBar => m_Wrapper.m_DeveloperInterface_ToggleMenuBar;
            public InputAction @ToggleStatusBar => m_Wrapper.m_DeveloperInterface_ToggleStatusBar;
            public InputAction @ToggleActivityBar => m_Wrapper.m_DeveloperInterface_ToggleActivityBar;
            public InputAction @ToggleSideBar => m_Wrapper.m_DeveloperInterface_ToggleSideBar;
            public InputAction @TogglePanel => m_Wrapper.m_DeveloperInterface_TogglePanel;
            public InputAction @Screenshot => m_Wrapper.m_DeveloperInterface_Screenshot;
            public InputActionMap Get() { return m_Wrapper.m_DeveloperInterface; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DeveloperInterfaceActions set) { return set.Get(); }
            public void SetCallbacks(IDeveloperInterfaceActions instance)
            {
                if (m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface != null)
                {
                    @ToggleDeveloperInterface.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleDeveloperInterface;
                    @ToggleDeveloperInterface.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleDeveloperInterface;
                    @ToggleDeveloperInterface.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleDeveloperInterface;
                    @OpenCommandPalette.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnOpenCommandPalette;
                    @OpenCommandPalette.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnOpenCommandPalette;
                    @OpenCommandPalette.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnOpenCommandPalette;
                    @ToggleMenuBar.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleMenuBar;
                    @ToggleMenuBar.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleMenuBar;
                    @ToggleMenuBar.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleMenuBar;
                    @ToggleStatusBar.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleStatusBar;
                    @ToggleStatusBar.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleStatusBar;
                    @ToggleStatusBar.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleStatusBar;
                    @ToggleActivityBar.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleActivityBar;
                    @ToggleActivityBar.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleActivityBar;
                    @ToggleActivityBar.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleActivityBar;
                    @ToggleSideBar.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleSideBar;
                    @ToggleSideBar.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleSideBar;
                    @ToggleSideBar.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnToggleSideBar;
                    @TogglePanel.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnTogglePanel;
                    @TogglePanel.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnTogglePanel;
                    @TogglePanel.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnTogglePanel;
                    @Screenshot.started -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnScreenshot;
                    @Screenshot.performed -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnScreenshot;
                    @Screenshot.canceled -= m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface.OnScreenshot;
                }
                m_Wrapper.m_DeveloperInterfaceActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ToggleDeveloperInterface.started += instance.OnToggleDeveloperInterface;
                    @ToggleDeveloperInterface.performed += instance.OnToggleDeveloperInterface;
                    @ToggleDeveloperInterface.canceled += instance.OnToggleDeveloperInterface;
                    @OpenCommandPalette.started += instance.OnOpenCommandPalette;
                    @OpenCommandPalette.performed += instance.OnOpenCommandPalette;
                    @OpenCommandPalette.canceled += instance.OnOpenCommandPalette;
                    @ToggleMenuBar.started += instance.OnToggleMenuBar;
                    @ToggleMenuBar.performed += instance.OnToggleMenuBar;
                    @ToggleMenuBar.canceled += instance.OnToggleMenuBar;
                    @ToggleStatusBar.started += instance.OnToggleStatusBar;
                    @ToggleStatusBar.performed += instance.OnToggleStatusBar;
                    @ToggleStatusBar.canceled += instance.OnToggleStatusBar;
                    @ToggleActivityBar.started += instance.OnToggleActivityBar;
                    @ToggleActivityBar.performed += instance.OnToggleActivityBar;
                    @ToggleActivityBar.canceled += instance.OnToggleActivityBar;
                    @ToggleSideBar.started += instance.OnToggleSideBar;
                    @ToggleSideBar.performed += instance.OnToggleSideBar;
                    @ToggleSideBar.canceled += instance.OnToggleSideBar;
                    @TogglePanel.started += instance.OnTogglePanel;
                    @TogglePanel.performed += instance.OnTogglePanel;
                    @TogglePanel.canceled += instance.OnTogglePanel;
                    @Screenshot.started += instance.OnScreenshot;
                    @Screenshot.performed += instance.OnScreenshot;
                    @Screenshot.canceled += instance.OnScreenshot;
                }
            }
        }
        public DeveloperInterfaceActions @DeveloperInterface => new DeveloperInterfaceActions(this);

        // Main Menu
        private readonly InputActionMap m_MainMenu;
        private IMainMenuActions m_MainMenuActionsCallbackInterface;
        public struct MainMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public MainMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
            public void SetCallbacks(IMainMenuActions instance)
            {
                if (m_Wrapper.m_MainMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_MainMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public MainMenuActions @MainMenu => new MainMenuActions(this);

        // Generic Menu
        private readonly InputActionMap m_GenericMenu;
        private IGenericMenuActions m_GenericMenuActionsCallbackInterface;
        private readonly InputAction m_GenericMenu_Navigate;
        private readonly InputAction m_GenericMenu_Submit;
        private readonly InputAction m_GenericMenu_Cancel;
        private readonly InputAction m_GenericMenu_Point;
        private readonly InputAction m_GenericMenu_Click;
        private readonly InputAction m_GenericMenu_Back;
        private readonly InputAction m_GenericMenu_Apply;
        private readonly InputAction m_GenericMenu_Default;
        public struct GenericMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public GenericMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_GenericMenu_Navigate;
            public InputAction @Submit => m_Wrapper.m_GenericMenu_Submit;
            public InputAction @Cancel => m_Wrapper.m_GenericMenu_Cancel;
            public InputAction @Point => m_Wrapper.m_GenericMenu_Point;
            public InputAction @Click => m_Wrapper.m_GenericMenu_Click;
            public InputAction @Back => m_Wrapper.m_GenericMenu_Back;
            public InputAction @Apply => m_Wrapper.m_GenericMenu_Apply;
            public InputAction @Default => m_Wrapper.m_GenericMenu_Default;
            public InputActionMap Get() { return m_Wrapper.m_GenericMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GenericMenuActions set) { return set.Get(); }
            public void SetCallbacks(IGenericMenuActions instance)
            {
                if (m_Wrapper.m_GenericMenuActionsCallbackInterface != null)
                {
                    @Navigate.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnNavigate;
                    @Navigate.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnNavigate;
                    @Navigate.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnNavigate;
                    @Submit.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnSubmit;
                    @Submit.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnSubmit;
                    @Submit.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnSubmit;
                    @Cancel.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnCancel;
                    @Cancel.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnCancel;
                    @Cancel.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnCancel;
                    @Point.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnPoint;
                    @Point.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnPoint;
                    @Point.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnPoint;
                    @Click.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnClick;
                    @Click.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnClick;
                    @Click.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnClick;
                    @Back.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnBack;
                    @Back.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnBack;
                    @Back.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnBack;
                    @Apply.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnApply;
                    @Apply.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnApply;
                    @Apply.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnApply;
                    @Default.started -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnDefault;
                    @Default.performed -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnDefault;
                    @Default.canceled -= m_Wrapper.m_GenericMenuActionsCallbackInterface.OnDefault;
                }
                m_Wrapper.m_GenericMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Navigate.started += instance.OnNavigate;
                    @Navigate.performed += instance.OnNavigate;
                    @Navigate.canceled += instance.OnNavigate;
                    @Submit.started += instance.OnSubmit;
                    @Submit.performed += instance.OnSubmit;
                    @Submit.canceled += instance.OnSubmit;
                    @Cancel.started += instance.OnCancel;
                    @Cancel.performed += instance.OnCancel;
                    @Cancel.canceled += instance.OnCancel;
                    @Point.started += instance.OnPoint;
                    @Point.performed += instance.OnPoint;
                    @Point.canceled += instance.OnPoint;
                    @Click.started += instance.OnClick;
                    @Click.performed += instance.OnClick;
                    @Click.canceled += instance.OnClick;
                    @Back.started += instance.OnBack;
                    @Back.performed += instance.OnBack;
                    @Back.canceled += instance.OnBack;
                    @Apply.started += instance.OnApply;
                    @Apply.performed += instance.OnApply;
                    @Apply.canceled += instance.OnApply;
                    @Default.started += instance.OnDefault;
                    @Default.performed += instance.OnDefault;
                    @Default.canceled += instance.OnDefault;
                }
            }
        }
        public GenericMenuActions @GenericMenu => new GenericMenuActions(this);

        // In Game Menu
        private readonly InputActionMap m_InGameMenu;
        private IInGameMenuActions m_InGameMenuActionsCallbackInterface;
        public struct InGameMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public InGameMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_InGameMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(InGameMenuActions set) { return set.Get(); }
            public void SetCallbacks(IInGameMenuActions instance)
            {
                if (m_Wrapper.m_InGameMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_InGameMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public InGameMenuActions @InGameMenu => new InGameMenuActions(this);

        // Pause Menu
        private readonly InputActionMap m_PauseMenu;
        private IPauseMenuActions m_PauseMenuActionsCallbackInterface;
        public struct PauseMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public PauseMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_PauseMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PauseMenuActions set) { return set.Get(); }
            public void SetCallbacks(IPauseMenuActions instance)
            {
                if (m_Wrapper.m_PauseMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_PauseMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public PauseMenuActions @PauseMenu => new PauseMenuActions(this);

        // Death Menu
        private readonly InputActionMap m_DeathMenu;
        private IDeathMenuActions m_DeathMenuActionsCallbackInterface;
        public struct DeathMenuActions
        {
            private @KOCInputActions m_Wrapper;
            public DeathMenuActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_DeathMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DeathMenuActions set) { return set.Get(); }
            public void SetCallbacks(IDeathMenuActions instance)
            {
                if (m_Wrapper.m_DeathMenuActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_DeathMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public DeathMenuActions @DeathMenu => new DeathMenuActions(this);

        // Loading Screen
        private readonly InputActionMap m_LoadingScreen;
        private ILoadingScreenActions m_LoadingScreenActionsCallbackInterface;
        public struct LoadingScreenActions
        {
            private @KOCInputActions m_Wrapper;
            public LoadingScreenActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_LoadingScreen; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LoadingScreenActions set) { return set.Get(); }
            public void SetCallbacks(ILoadingScreenActions instance)
            {
                if (m_Wrapper.m_LoadingScreenActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_LoadingScreenActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public LoadingScreenActions @LoadingScreen => new LoadingScreenActions(this);

        // Splash Screen
        private readonly InputActionMap m_SplashScreen;
        private ISplashScreenActions m_SplashScreenActionsCallbackInterface;
        private readonly InputAction m_SplashScreen_Continue;
        public struct SplashScreenActions
        {
            private @KOCInputActions m_Wrapper;
            public SplashScreenActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Continue => m_Wrapper.m_SplashScreen_Continue;
            public InputActionMap Get() { return m_Wrapper.m_SplashScreen; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SplashScreenActions set) { return set.Get(); }
            public void SetCallbacks(ISplashScreenActions instance)
            {
                if (m_Wrapper.m_SplashScreenActionsCallbackInterface != null)
                {
                    @Continue.started -= m_Wrapper.m_SplashScreenActionsCallbackInterface.OnContinue;
                    @Continue.performed -= m_Wrapper.m_SplashScreenActionsCallbackInterface.OnContinue;
                    @Continue.canceled -= m_Wrapper.m_SplashScreenActionsCallbackInterface.OnContinue;
                }
                m_Wrapper.m_SplashScreenActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Continue.started += instance.OnContinue;
                    @Continue.performed += instance.OnContinue;
                    @Continue.canceled += instance.OnContinue;
                }
            }
        }
        public SplashScreenActions @SplashScreen => new SplashScreenActions(this);

        // Start Screen
        private readonly InputActionMap m_StartScreen;
        private IStartScreenActions m_StartScreenActionsCallbackInterface;
        private readonly InputAction m_StartScreen_Continue;
        public struct StartScreenActions
        {
            private @KOCInputActions m_Wrapper;
            public StartScreenActions(@KOCInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Continue => m_Wrapper.m_StartScreen_Continue;
            public InputActionMap Get() { return m_Wrapper.m_StartScreen; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(StartScreenActions set) { return set.Get(); }
            public void SetCallbacks(IStartScreenActions instance)
            {
                if (m_Wrapper.m_StartScreenActionsCallbackInterface != null)
                {
                    @Continue.started -= m_Wrapper.m_StartScreenActionsCallbackInterface.OnContinue;
                    @Continue.performed -= m_Wrapper.m_StartScreenActionsCallbackInterface.OnContinue;
                    @Continue.canceled -= m_Wrapper.m_StartScreenActionsCallbackInterface.OnContinue;
                }
                m_Wrapper.m_StartScreenActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Continue.started += instance.OnContinue;
                    @Continue.performed += instance.OnContinue;
                    @Continue.canceled += instance.OnContinue;
                }
            }
        }
        public StartScreenActions @StartScreen => new StartScreenActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnFire(InputAction.CallbackContext context);
        }
        public interface IDeveloperInterfaceActions
        {
            void OnToggleDeveloperInterface(InputAction.CallbackContext context);
            void OnOpenCommandPalette(InputAction.CallbackContext context);
            void OnToggleMenuBar(InputAction.CallbackContext context);
            void OnToggleStatusBar(InputAction.CallbackContext context);
            void OnToggleActivityBar(InputAction.CallbackContext context);
            void OnToggleSideBar(InputAction.CallbackContext context);
            void OnTogglePanel(InputAction.CallbackContext context);
            void OnScreenshot(InputAction.CallbackContext context);
        }
        public interface IMainMenuActions
        {
        }
        public interface IGenericMenuActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnBack(InputAction.CallbackContext context);
            void OnApply(InputAction.CallbackContext context);
            void OnDefault(InputAction.CallbackContext context);
        }
        public interface IInGameMenuActions
        {
        }
        public interface IPauseMenuActions
        {
        }
        public interface IDeathMenuActions
        {
        }
        public interface ILoadingScreenActions
        {
        }
        public interface ISplashScreenActions
        {
            void OnContinue(InputAction.CallbackContext context);
        }
        public interface IStartScreenActions
        {
            void OnContinue(InputAction.CallbackContext context);
        }
    }
}
